server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiples-instances
          uri: https://github.com/emanuelquinto/Microservicios-Apis
          search-paths: config-data
  application:
    name: Config-Server
          
            
        